server:
  port: 9527
spring:
  application:
    name: cloud-gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true #开启从注册中心动态创建路由功能,利用微服务名进行路由
      routes:
        - id: payment_routh #路由的ID,没有固定规则但是要求唯一,建议配合服务名
          #uri: http://127.0.0.1:8001 #匹配后提供服务的路由地址
          uri: lb://CLOUD-PAYMENT-SERVICE
          predicates:
            - Path=/payment/getPaymentById/** #断言,路径相匹配的进行路由
            - Between=2021-01-06T23:34:02.855+08:00[Asia/Shanghai],2021-01-10T23:34:03.855+08:00[Asia/Shanghai] #必须在两个时间内访问
            #- Cookie=username,wcy #必须携带cookie访问
        - id: payment_routh2 #路由的ID,没有固定规则但是要求唯一,建议配合服务名
          #uri: http://127.0.0.1:8001 #匹配后提供服务的路由地址
          uri: lb://CLOUD-PAYMENT-SERVICE
          predicates:
            - Path=/payment/create/** #断言,路径相匹配的进行路由
eureka:
  instance:
    hostname: cloud-gateway-service
  client:
    #表示是否将自己注册到eureka 默认是true
    register-with-eureka: true
    #是否从eurekaServer抓取已有的注册信息,默认为true。单节点无所谓,集群必须设置true才能配合ribbon使用负载均衡
    fetch-registry: true
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka/,http://eureka7002.com:7002/eureka/ #集群版
